bouquetshop/config/routes.rb
Rails.application.routes.draw do
root 'bouquets#home'
resources :bouquets

  get 'bouquets/home'
   get 'home' => 'bouquets#home', :as => 'home'

  get 'bouquets/new'
  get 'new' => 'bouquets#new', :as => 'new'
  
   get 'bouquets/show'
  get 'show' => 'bouquets#show', :as => 'show'

  get 'bouquets/edit'
  get 'edit/:id' => 'bouquets#edit', :as => 'edit'
  
  get 'bouquets/view'
  get 'view/:id' => 'bouquets#view', :as => 'view'
  
   get 'delete/:id' => 'bouquets#delete', :as => 'delete'
 

  get 'bouquets/:id', to: 'bouquets#view'
  get 'bouquets/:id', to: 'bouquets#edit' 
  get 'bouquets/:id', to: 'bouquets#delete' 
   

end

bouquetshop/app/models/bouquet.rb
class Bouquet < ActiveRecord::Base
end

bouquetshop/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

bouquetshop/app/controllers/bouquets_controller.rb
class BouquetsController < ApplicationController

  def home
  @bouquets = Bouquet.all
  end

  def new
  
  end 
  
 def create
 @bouquet = Bouquet.new(bouquet_params)
  flowers = params[:flowers]
 if flowers.nil?
 flash.now[:notice]="EROOOOOO"
 redirect_to show_url
 else
  
 @bouquet.flowers = flowers.join(" ")
  if @bouquet.save
            redirect_to home_url
      else
            @bouquets = Bouquet.find(:all)
            render :action => 'new'
      end
end
end
 
 
 def destroy
      Bouquet.find(params[:id]).destroy
      redirect_to home_url
   end
  
  def delete
      Bouquet.find(params[:id]).destroy
      redirect_to home_url
   end
  def edit
  
  @bouquets=Bouquet.find(params[:id]) 
  @flowers = @bouquets.flowers
  @flowers=@flowers.split(" ")
 
   end
 
  def show
 
 
  end
 
  def view
  @bouquets=Bouquet.find(params[:id]) 
 # id=@bouquets.attributes['id']
 
  end

 def update
  @bouquets = Bouquet.find(params[:id])
flowers = params[:flowers]
 @bouquets.flowers = flowers.join(" ")
  if @bouquets.update(bouquet_params)
    render 'view'
  else
    render 'edit'
  end
end

  
  def bouquet_params
    params.require(:bouquet).permit(:name, :category, :arrangement, :occasion, :h_delivery, :flowers, :price)
end

end

bouquetshop/app/helpers/application_helper.rb
module ApplicationHelper
end

bouquetshop/app/helpers/bouquets_helper.rb
module BouquetsHelper
end

bouquetshop/app/views/bouquets/_form.html.erb
<%= form_for @bouquets do |f| %>

 
<p>
    <%= f.label "Bouquet-Name" %><br>
    <%= f.text_field :name %>

  </p>
  
 
<p>Type<br>
  <%= f.radio_button :category, 'Bouquet' %><b>Bouquet</b>
  <%= f.radio_button :category, 'Corsage' %><b>Corsage</b>
  <%= f.radio_button :category, 'Reath' %><b>Reath</b>
 
</p>
  
<p>Arrangement- Style<br> 
 <%= f.select :arrangement, options_for_select(%w[Basket Handtied Plants Posy ]) %>
</p>

<p>Occasion<br>
<%= f.select :occasion, options_for_select(%w[Wedding Birthday Funeral Prom Everyday]) %>
</p>	

<p>
    <%= f.label "Price" %><br>
    <%= f.text_field :price %>
  </p>
  

<p> Home Delivery Applicable 

  <%= f.radio_button :h_delivery, 'true' %><b>Yes</b>
  <%= f.radio_button :h_delivery, 'false' %><b>No</b>
 </p>
  
 <p>
    <%= f.submit %>
  </p>
<% end %>

bouquetshop/app/views/bouquets/edit.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>Kriti's Creations</title>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<link href="default.css" rel="stylesheet" type="text/css" />

</head>
<body>
<div id="content">
  <div id="colOne">
    <div id="header">
      <h1><a href="#">Kriti's Creations</a></h1>
    </div>
    <div class="post">
      <h2 class="title">Welcome..!</h2>
      <div class="story">
        <p><em><strong>Make your changes here</strong></em> 
		</div>
      <div class="meta">
       
      </div>
    </div>
    <div class="post">
      <h2 class="title"></h2>
  
      <div class="story">
 
<%= form_for @bouquets do |f| %>
<p>
    <%= f.label "Bouquet-Name" %><br>
    <%= f.text_field :name %>

  </p>
<p>Type<br>
  <%= f.radio_button :category, 'Bouquet' %><b>Bouquet</b>
  <%= f.radio_button :category, 'Corsage' %><b>Corsage</b>
  <%= f.radio_button :category, 'Reath' %><b>Reath</b>
 
</p>
<p>Arrangement- Style<br> 
 <%= f.select :arrangement, options_for_select(%w[Basket Handtied Plants Posy ]) %>
</p>

<p>Occasion<br>
<%= f.select :occasion, options_for_select(%w[Wedding Birthday Funeral Prom Everyday]) %>
</p>	

<p>
    <%= f.label "Price" %><br>
    <%= f.text_field :price %>
  </p>
  

<p> Home Delivery Applicable 

  <%= f.radio_button :h_delivery, 'true' %><b>Yes</b>
  <%= f.radio_button :h_delivery, 'false' %><b>No</b>
 </p>
  

<p> Flowers Included <br>

<% if @flowers.include? "Rose" %>
<input id="flowers" name="flowers[]" type="checkbox" value="Rose" checked/> Rose
<% else %>
<input id="flowers" name="flowers[]" type="checkbox" value="Rose" /> Rose
<% end %>

<% if @flowers.include? "Lily" %>
<input id="flowers" name="flowers[]" type="checkbox" value="Lily" checked/> Lily
<% else %>
<input id="flowers" name="flowers[]" type="checkbox" value="Lily" /> Lily
<% end %>

<% if @flowers.include? "Tuberosa" %>
<input id="flowers" name="flowers[]" type="checkbox" value="Tuberosa" checked/> Tuberosa
<% else %>
<input id="flowers" name="flowers[]" type="checkbox" value="Tuberosa" /> Tuberosa
<% end %>

<% if @flowers.include? "Dahlia" %>
<input id="flowers" name="flowers[]" type="checkbox" value="Dahlia" checked/> Dahlia
<% else %>
<input id="flowers" name="flowers[]" type="checkbox" value="Dahlia" /> Dahlia
<% end %>

<% if @flowers.include? "Orchids" %>
<input id="flowers" name="flowers[]" type="checkbox" value="Orchids" checked/> Orchids
<% else %>
<input id="flowers" name="flowers[]" type="checkbox" value="Orchids" /> Orchids
<% end %>
<br>

<% if @flowers.include? "Chrysanthemum" %>
<input id="flowers" name="flowers[]" type="checkbox" value="Chrysanthemum" checked/> Chrysanthemum
<% else %>
<input id="flowers" name="flowers[]" type="checkbox" value="Chrysanthemum" /> Chrysanthemum
<% end %>

<% if @flowers.include? "Aster" %>
<input id="flowers" name="flowers[]" type="checkbox" value="Aster" checked/> Aster
<% else %>
<input id="flowers" name="flowers[]" type="checkbox" value="Aster" /> Aster
<% end %>

<% if @flowers.include? "Sunflower" %>
<input id="flowers" name="flowers[]" type="checkbox" value="Sunflower" checked/> Sunflower
<% else %>
<input id="flowers" name="flowers[]" type="checkbox" value="Sunflower" /> Sunflower
<% end %>

<% if @flowers.include? "Daisy" %>
<input id="flowers" name="flowers[]" type="checkbox" value="Daisy" checked/> Daisy
<% else %>
<input id="flowers" name="flowers[]" type="checkbox" value="Daisy" /> Daisy
<% end %>
<p>
    <%= f.submit %>
  </p>
<% end %>

 
      </div>
    
    </div>
  </div>
  <div id="colTwo">
    <ul>
      <li id="menu">
        <h2>Pages</h2>
        <ul>
        <li><%= link_to "Home", home_url %></li>   
 <li><%= link_to "New", new_url %></li>   		
	
        </ul>
      </li>
      <li>
        
           <h2>You can make the world happy if you are happy :)</h2>
      </li>

         <p> <blockquote>
		 “The earth laughs in flowers.”  ― Ralph Waldo Emerson
         </blockquote>
        </p>
		<p> <blockquote>
		“I must have flowers, always, and always.”  ― Claude Monet
         </blockquote>
    
   </p> 
 
    </ul>
  </div>
  <div style="clear: both;">&nbsp;</div>
</div>
<div id="footer">
  <p><strong>We are happy to have you as our visitors</strong></a></p>
</div>
</body>
</html>

bouquetshop/app/views/bouquets/home.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>Gumamela</title>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<link href="default.css" rel="stylesheet" type="text/css" />
</head>
<body>
<div id="content">
  <div id="colOne">
    <div id="header">
      <h1><a href="#">Kriti's Creations</a></h1>
   
    </div>
    <div class="post">
      <h2 class="title">Welcome..!</h2>
            <div class="story">
        <p><em><strong>Kriti's Creations</strong></em> has come a long way in the business of flower and making others happy. Check out some of our bouquets available :) </p>
      </div>
      <div class="meta">
      </div>
    </div>
    <div class="post">
      <h2 class="title">Available Bouquets</h2>
      <div class="story">
      
        <table>
    		
<form action="#n" name="theForm">			
			<% @bouquets.each do |bouquet| %>
    <tr> </tr>
	
	<tr>
      <td><%= bouquet.name %> </td>
	  <td> </td> 
	
	  <td> </td>
	  <td><input type= "radio" name="Select" value=<%= bouquet.id %> id="s" onclick="foo()" > </td>
	 
	  
    </tr>

<% end %>

<p>

<input type="button" name="View" value="View" id="1" onClick="view()" disabled>
<input type="button" name="Edit" value="Edit" id="2" onClick="edit()" disabled>
<input type="button" name="Delete" value="Delete" id="3" onClick="func_delete()" disabled>


</table>

 
      </div>
      <div class="meta">
       
      </div>
    </div>
  </div>
  <div id="colTwo">
    <ul>
      <li id="menu">
        <h2>Pages</h2>
        <ul>
          <li class="active"><a href="#">Home</a></li>
		 
		  <li><%= link_to "New", new_url %></li>            
		
        </ul>
      </li>
      <li>
        <h2>You can make the world happy if you are happy :)</h2>
       
      </li>

        <p> <blockquote>
		 “The earth laughs in flowers.”  ― Ralph Waldo Emerson
       </blockquote> </p>
	   <p> <blockquote>
		“I must have flowers, always, and always.”  ― Claude Monet
         </blockquote>
    
   </p> 
 
      
    </ul>
  </div>
  <div style="clear: both;">&nbsp;</div>
</div>
<div id="footer">
 <p><strong>We are happy to have you as our visitors</strong></a></p>
</div>
</body>

<script>
function foo()
{
	document.getElementById("1").disabled= false;
	document.getElementById("2").disabled= false;
	document.getElementById("3").disabled= false;
	
}
</script>
<script>
function func_delete()
{
	var x= document.getElementsByName("Select");
	var val;
	for( var i=0; i< x.length; i++)
	{
		if(x[i].type == "radio" && x[i].checked)
		{
			val= x[i].value;
			break;
		}
				
	}
	var result= confirm("Are you sure you want to delete the selected item?");
	if (result==true)
{	document.forms[0].action ="/delete/"+val+"/";
	document.forms[0].submit();}
   
}
</script>

<script>
function edit()
{
	
	var etemp= document.getElementsByName("Select");
	var e;
	for( var i=0; i< etemp.length; i++)
	{
		if(etemp[i].type == "radio" && etemp[i].checked)
		{
			e= etemp[i].value;
			break;
		}
				
	}
	document.forms[0].action ="/edit/"+e+"/";
	document.forms[0].submit();
}
</script>

<script>
function view()
{
	var vtemp= document.getElementsByName("Select");
	var v;
	
	for( var i=0; i< vtemp.length; i++)
	{
		if(vtemp[i].type == "radio" && vtemp[i].checked)
		{
			v= vtemp[i].value;
			
			break;
		}

	}
	
	document.forms[0].action ="/view/"+v+"/";
	document.forms[0].submit();
}
</script>
</html>

bouquetshop/app/views/bouquets/new.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>Kriti's Creations</title>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<link href="default.css" rel="stylesheet" type="text/css" />

</head>
<body>
<div id="content">
  <div id="colOne">
    <div id="header">
      <h1><a href="#">Kriti's Creations</a></h1>
    </div>
    <div class="post">
      <h2 class="title">Welcome..!</h2>
      <div class="story">
        <p><em><strong>Add a new Bouquet Idea here..</strong></em> 
		</div>
      <div class="meta">
       
      </div>
    </div>
    <div class="post">
      <h2 class="title"></h2>
  
      <div class="story">
       
<%= form_for :bouquet, url: bouquets_path do |f| %>

  <p>
    <%= f.label "Bouquet-Name" %><br>
    <%= f.text_field :name %>
  </p>
  
  <p>Type<br>
  <%= f.radio_button :category, 'Bouquet' %><b>Bouquet</b>
  <%= f.radio_button :category, 'Corsage' %><b>Corsage</b>
  <%= f.radio_button :category, 'Reath' %><b>Reath</b>
 
</p>
  
<p> Arrangement- Style<br> 
 <%= f.select :arrangement, options_for_select(%w[Basket Handtied Plants Posy ]) %>
</p>

<p>Occasion<br>
<%= f.select :occasion, options_for_select(%w[Wedding Birthday Funeral Prom Everyday]) %>
</p>	

<p>
    <%= f.label "Price" %><br>
    <%= f.text_field :price %>
  </p>
 
<p> Flowers Included <br>
 <input id="flowers" name="flowers[]" type="checkbox" value="Rose" /> Rose
	<input id="flowers" name="flowers[]" type="checkbox" value="Lily" /> Lily
	<input id="flowers" name="flowers[]" type="checkbox" value="Tuberosa" /> Tuberosa
<input id="flowers" name="flowers[]" type="checkbox" value="Dahlia" /> Dahlia	
<input id="flowers" name="flowers[]" type="checkbox" value="Orchids" /> Orchids
<br>
<input id="flowers" name="flowers[]" type="checkbox" value="Chrysanthemum" /> Chrysanthemum
<input id="flowers" name="flowers[]" type="checkbox" value="Aster" /> Aster

<input id="flowers" name="flowers[]" type="checkbox" value="Sunflower" /> Sunflower
<input id="flowers" name="flowers[]" type="checkbox" value="Daisy" /> Daisy


</p>

<p> Home Delivery Applicable 

  <%= f.radio_button :h_delivery, 'true' %><b>Yes</b>
  <%= f.radio_button :h_delivery, 'false' %><b>No</b>
 </p>
  
  <p>
    <%= f.submit %>
	
  </p>
<% end %>
       
      </div>
    
    </div>
  </div>
  <div id="colTwo">
    <ul>
      <li id="menu">
        <h2>Pages</h2>
        <ul>
        <li><%= link_to "Home", home_url %></li>            
		<li class="active"><a href="#">New</a></li> 
         
        </ul>
      </li>
      <li>
          <h2>You can make the world happy if you are happy :)</h2>
      
      </li>

         <p> <blockquote>
		 “The earth laughs in flowers.”  ― Ralph Waldo Emerson
         </blockquote>
        </p>
		<p> <blockquote>
		“I must have flowers, always, and always.”  ― Claude Monet
         </blockquote>
    
   </p> 
 
    </ul>
  </div>
  <div style="clear: both;">&nbsp;</div>
</div>
<div id="footer">
  <p><strong>We are happy to have you as our visitors</strong></a></p>
</div>

</body>
</html>

bouquetshop/app/views/bouquets/show.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>Kriti's Creations</title>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<link href="default.css" rel="stylesheet" type="text/css" />

</head>
<body>
<div id="content">
  <div id="colOne">
    <div id="header">
      <h1><a href="#">Kriti's Creations</a></h1>
    </div>
    <div class="post">
    
     
    
    </div>
    <div class="post">
      <h2 class="title"></h2>
  
      <div class="story">
       
 <h2>Ooops. You did not select any flowers for the new bouquet!! </h2>
 
 <%= link_to 'Go Back', :back %>


      </div>
    
    </div>
  </div>
  <div id="colTwo">
    <ul>
      <li id="menu">
        <h2>Pages</h2>
        <ul>

		<li><%= link_to "Home", home_url %></li> 
		<li><%= link_to "New", new_url %></li> 
       
        
        </ul>
      </li>
      <li>
          <h2>You can make the world happy if you are happy :)</h2>
      </li>

         <p> <blockquote>
		 “The earth laughs in flowers.”  ― Ralph Waldo Emerson
         </blockquote>
        </p>
		<p> <blockquote>
		“I must have flowers, always, and always.”  ― Claude Monet
         </blockquote>
    
   </p> 
 
      
    </ul>
  </div>
  <div style="clear: both;">&nbsp;</div>
</div>
<div id="footer">
  <p><strong>We are happy to have you as our visitors</strong></a></p>
</div>
</body>
</html>

bouquetshop/app/views/bouquets/view.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>Kriti's Creations</title>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<link href="default.css" rel="stylesheet" type="text/css" />

</head>
<body>
<div id="content">
  <div id="colOne">
    <div id="header">
      <h1><a href="#">Kriti's Creations</a></h1>
    </div>
    <div class="post">
      <h2 class="title">Welcome..!</h2>
     
    
    </div>
    <div class="post">
      <h2 class="title"></h2>
  
      <div class="story">
       

<h1>Your current Selection</h1>

 
    <table>

      <br>Name :<%= @bouquets.name %> </br>
	   <br>Category :<%= @bouquets.category %> </br>
	   <br>Arrangement :<%= @bouquets.arrangement %> </br>
	   <br>Occasion :<%= @bouquets.occasion %> </br>
	   <br>Flowers Included :<%= @bouquets.flowers %> </br>
	   <br>Price( in INR) :<%= @bouquets.price %> </br>
	    <br>Home Delivery Applicable :
	   <%= @bouquets.h_delivery? ? 'Yes' : 'No' %> </br>
       
	</table>
	<p>
    <%= link_to 'Go Back', :back %> </p>
      </div>
    
    </div>
  </div>
  <div id="colTwo">
    <ul>
      <li id="menu">
        <h2>Pages</h2>
        <ul>

		<li><%= link_to "Home", home_url %></li> 
		<li><%= link_to "New", new_url %></li> 
         
        </ul>
      </li>
      <li>
       
            <h2>You can make the world happy if you are happy :)</h2>
      
      </li>

         <p> <blockquote>
		 “The earth laughs in flowers.”  ― Ralph Waldo Emerson
         </blockquote>
        </p>
		<p> <blockquote>
		“I must have flowers, always, and always.”  ― Claude Monet
         </blockquote>
    
   </p> 
 
      
    </ul>
  </div>
  <div style="clear: both;">&nbsp;</div>
</div>
<div id="footer">
  <p><strong>We are happy to have you as our visitors</strong></a></p>
</div>
</body>
</html>

bouquetshop/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title> Kriti's Creations </title>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
 
 
  
  <%= csrf_meta_tags %>
</head>
<body>



      <%= yield %>
   
  </body>
</html>